In [1]:
from pathlib import Path

import pandas as pd

hermes_root = Path.cwd().parent

quarantine_base_dir = hermes_root / "data/quarantine/silver"

In [2]:
paths = sorted(quarantine_base_dir.glob("*/*.parquet"))

for path in paths:
    print(path)

/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/customers/not_null_postal_code.parquet
/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/orders/accepted_values_order_status.parquet
/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/orders/not_null_order_status.parquet

In [3]:
df_customers_not_null_postal_code = pd.read_parquet(str(paths[0]))

df_customers_not_null_postal_code

,customer_id,first_name,last_name,email,phone_number,city,region,postcode,loyalty_tier,creation_datetime,is_active,_silver_processed_at,_silver_processing_date,_quarantine_table_name,_quarantine_column_name,_quarantine_rule_name,_quarantine_failure_reason,_quarantine_time,_quarantine_date
0,CUSTOMER-000001,Victor,Chapman,geoffreyharris@example.net,028 9018 0328,Glasgow,Scotland,None,Bronze,2025-11-03 20:35:31.173527,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
1,CUSTOMER-000002,Karl,O'Sullivan,uakhtar@example.org,+44(0)114 4960848,Manchester,Greater Manchester,None,Bronze,2025-10-27 17:49:03.042373,False,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
2,CUSTOMER-000003,Marilyn,Campbell,spencerlindsey@example.net,+44117 496 0511,Newcastle,Tyne and Wear,None,Bronze,2026-02-20 14:24:12.080758,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
3,CUSTOMER-000004,Bruce,Cross,finchsophie@example.net,+44(0)2074960833,Cardiff,Wales,None,Silver,2026-05-10 10:56:34.787234,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
4,CUSTOMER-000005,Julia,Thomas,ann14@example.net,020 7946 0707,London,Greater London,None,Gold,2023-08-30 20:21:38.441925,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUSTOMER-000996,June,Shaw,qgreen@example.com,0121 496 0013,Liverpool,Merseyside,None,Bronze,2024-04-27 23:18:32.074593,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
996,CUSTOMER-000997,Nigel,Clements,jacksonpaige@example.net,(01632) 960 016,Leeds,West Yorkshire,None,Bronze,2025-01-29 04:43:50.645441,False,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
997,CUSTOMER-000998,Donald,Faulkner,thorpeleonard@example.org,(01632) 960 427,Cardiff,Wales,None,Gold,2024-06-15 18:29:50.338916,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
998,CUSTOMER-000999,Victor,Riley,clarkbrenda@example.org,01174960779,Bristol,Bristol,None,Platinum,2024-05-09 11:14:55.011066,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
999,CUSTOMER-001000,Charlotte,Wilson,yvonne81@example.org,+44(0)1154960881,Newcastle,Tyne and Wear,None,Bronze,2024-08-28 22:31:58.467805,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05

In [4]:
for path in paths:
    print(str(path))
    df = pd.read_parquet(str(path))
    display(df)

/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/customers/not_null_postal_code.parquet

,customer_id,first_name,last_name,email,phone_number,city,region,postcode,loyalty_tier,creation_datetime,is_active,_silver_processed_at,_silver_processing_date,_quarantine_table_name,_quarantine_column_name,_quarantine_rule_name,_quarantine_failure_reason,_quarantine_time,_quarantine_date
0,CUSTOMER-000001,Victor,Chapman,geoffreyharris@example.net,028 9018 0328,Glasgow,Scotland,None,Bronze,2025-11-03 20:35:31.173527,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
1,CUSTOMER-000002,Karl,O'Sullivan,uakhtar@example.org,+44(0)114 4960848,Manchester,Greater Manchester,None,Bronze,2025-10-27 17:49:03.042373,False,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
2,CUSTOMER-000003,Marilyn,Campbell,spencerlindsey@example.net,+44117 496 0511,Newcastle,Tyne and Wear,None,Bronze,2026-02-20 14:24:12.080758,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
3,CUSTOMER-000004,Bruce,Cross,finchsophie@example.net,+44(0)2074960833,Cardiff,Wales,None,Silver,2026-05-10 10:56:34.787234,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
4,CUSTOMER-000005,Julia,Thomas,ann14@example.net,020 7946 0707,London,Greater London,None,Gold,2023-08-30 20:21:38.441925,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUSTOMER-000996,June,Shaw,qgreen@example.com,0121 496 0013,Liverpool,Merseyside,None,Bronze,2024-04-27 23:18:32.074593,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
996,CUSTOMER-000997,Nigel,Clements,jacksonpaige@example.net,(01632) 960 016,Leeds,West Yorkshire,None,Bronze,2025-01-29 04:43:50.645441,False,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
997,CUSTOMER-000998,Donald,Faulkner,thorpeleonard@example.org,(01632) 960 427,Cardiff,Wales,None,Gold,2024-06-15 18:29:50.338916,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
998,CUSTOMER-000999,Victor,Riley,clarkbrenda@example.org,01174960779,Bristol,Bristol,None,Platinum,2024-05-09 11:14:55.011066,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05
999,CUSTOMER-001000,Charlotte,Wilson,yvonne81@example.org,+44(0)1154960881,Newcastle,Tyne and Wear,None,Bronze,2024-08-28 22:31:58.467805,True,2026-07-05 21:40:56.460850,2026-07-05,customers,postal_code,not_null,Column does not exist: postal_code,2026-07-05 21:47:05.006547,2026-07-05

/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/orders/accepted_values_order_status.parquet

,order_id,customer_id,store_id,channel,status,order_timestamp,currency,gross_amount,discount_amount,net_amount,...,source_file_date,customer_note,_silver_processed_at,_silver_processing_date,_quarantine_table_name,_quarantine_column_name,_quarantine_rule_name,_quarantine_failure_reason,_quarantine_time,_quarantine_date
0,ORDER-00000001,CUSTOMER-000279,None,online,confirmed,2023-01-21 10:15:39,GBP,1162.90,100.08,1062.82,...,2023-01-21,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
1,ORDER-00000002,CUSTOMER-000174,None,mobile_app,confirmed,2023-01-28 07:47:22,GBP,851.82,0.00,851.82,...,2023-01-28,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
2,ORDER-00000003,CUSTOMER-000993,None,online,returned,2023-01-13 13:10:25,GBP,492.06,0.00,492.06,...,2023-01-13,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
3,ORDER-00000004,CUSTOMER-000377,STORE-0011,store,confirmed,2023-01-02 05:03:46,GBP,178.35,0.00,178.35,...,2023-01-02,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
4,ORDER-00000005,CUSTOMER-000285,None,online,fulfilled,2023-01-24 08:21:12,GBP,191.41,9.57,181.84,...,2023-01-24,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,ORDER-00004996,CUSTOMER-000207,None,online,confirmed,2023-01-09 07:09:42,GBP,485.38,0.00,485.38,...,2023-01-09,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
4996,ORDER-00004997,CUSTOMER-000771,STORE-0019,store,returned,2023-01-21 19:33:30,GBP,403.98,0.00,403.98,...,2023-01-21,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
4997,ORDER-00004998,CUSTOMER-000806,None,online,fulfilled,2023-01-21 23:47:11,GBP,678.38,0.00,678.38,...,2023-01-21,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
4998,ORDER-00004999,CUSTOMER-000173,STORE-0013,store,fulfilled,2023-01-01 10:45:58,GBP,467.22,0.00,467.22,...,2023-01-01,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05
4999,ORDER-00005000,CUSTOMER-000850,None,online,confirmed,2023-01-28 03:43:35,GBP,228.86,0.00,228.86,...,2023-01-28,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,accepted_values,Column does not exist: order_status,2026-07-05 21:47:17.654900,2026-07-05

/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/orders/not_null_order_status.parquet

,order_id,customer_id,store_id,channel,status,order_timestamp,currency,gross_amount,discount_amount,net_amount,...,source_file_date,customer_note,_silver_processed_at,_silver_processing_date,_quarantine_table_name,_quarantine_column_name,_quarantine_rule_name,_quarantine_failure_reason,_quarantine_time,_quarantine_date
0,ORDER-00000001,CUSTOMER-000279,None,online,confirmed,2023-01-21 10:15:39,GBP,1162.90,100.08,1062.82,...,2023-01-21,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
1,ORDER-00000002,CUSTOMER-000174,None,mobile_app,confirmed,2023-01-28 07:47:22,GBP,851.82,0.00,851.82,...,2023-01-28,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
2,ORDER-00000003,CUSTOMER-000993,None,online,returned,2023-01-13 13:10:25,GBP,492.06,0.00,492.06,...,2023-01-13,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
3,ORDER-00000004,CUSTOMER-000377,STORE-0011,store,confirmed,2023-01-02 05:03:46,GBP,178.35,0.00,178.35,...,2023-01-02,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
4,ORDER-00000005,CUSTOMER-000285,None,online,fulfilled,2023-01-24 08:21:12,GBP,191.41,9.57,181.84,...,2023-01-24,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,ORDER-00004996,CUSTOMER-000207,None,online,confirmed,2023-01-09 07:09:42,GBP,485.38,0.00,485.38,...,2023-01-09,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
4996,ORDER-00004997,CUSTOMER-000771,STORE-0019,store,returned,2023-01-21 19:33:30,GBP,403.98,0.00,403.98,...,2023-01-21,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
4997,ORDER-00004998,CUSTOMER-000806,None,online,fulfilled,2023-01-21 23:47:11,GBP,678.38,0.00,678.38,...,2023-01-21,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
4998,ORDER-00004999,CUSTOMER-000173,STORE-0013,store,fulfilled,2023-01-01 10:45:58,GBP,467.22,0.00,467.22,...,2023-01-01,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05
4999,ORDER-00005000,CUSTOMER-000850,None,online,confirmed,2023-01-28 03:43:35,GBP,228.86,0.00,228.86,...,2023-01-28,None,2026-07-05 21:41:04.089282,2026-07-05,orders,order_status,not_null,Column does not exist: order_status,2026-07-05 21:47:17.179532,2026-07-05

In [5]:
for path in paths:
    print(str(path))
    df = pd.read_parquet(str(path))
    print(df.describe())

/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/customers/not_null_postal_code.parquet
                   creation_datetime           _silver_processed_at  \
count                           1000                           1000
mean   2024-12-02 16:51:52.047403776  2026-07-05 21:40:56.460849152
min       2023-07-06 22:06:25.500977     2026-07-05 21:40:56.460850
25%    2024-03-17 00:50:33.918766848  2026-07-05 21:40:56.460849920
50%    2024-11-16 23:53:28.084078336  2026-07-05 21:40:56.460849920
75%    2025-08-13 11:24:07.014640128  2026-07-05 21:40:56.460849920
max       2026-06-05 11:13:29.170429     2026-07-05 21:40:56.460850

                    _quarantine_time
count                           1000
mean   2026-07-05 21:47:05.006547200
min       2026-07-05 21:47:05.006547
25%    2026-07-05 21:47:05.006546944
50%    2026-07-05 21:47:05.006546944
75%    2026-07-05 21:47:05.006546944
max       2026-07-05 21:47:05.006547
/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/orders/accepted_values_order_status.parquet
                     order_timestamp  gross_amount  discount_amount  \
count                           5000   5000.000000      5000.000000
mean   2023-01-16 11:12:56.385199872    635.460056        13.873348
min              2023-01-01 00:02:36      7.150000         0.000000
25%    2023-01-08 19:21:18.750000128    252.697500         0.000000
50%              2023-01-16 10:06:34    471.060000         0.000000
75%    2023-01-24 01:32:52.249999872    881.402500        18.470000
max              2023-01-31 23:57:57   4029.280000       287.960000
std                              NaN    529.537228        26.291518

        net_amount   tax_amount           _silver_processed_at  \
count  5000.000000  5000.000000                           5000
mean    621.586708   124.317036  2026-07-05 21:41:04.089282560
min       6.430000     1.290000     2026-07-05 21:41:04.089282
25%     248.350000    49.670000  2026-07-05 21:41:04.089282048
50%     457.925000    91.585000  2026-07-05 21:41:04.089282048
75%     862.047500   172.407500  2026-07-05 21:41:04.089282048
max    3955.970000   791.180000     2026-07-05 21:41:04.089282
std     517.542541   103.508408                            NaN

                    _quarantine_time
count                           5000
mean   2026-07-05 21:47:17.654900224
min       2026-07-05 21:47:17.654900
25%    2026-07-05 21:47:17.654899968
50%    2026-07-05 21:47:17.654899968
75%    2026-07-05 21:47:17.654899968
max       2026-07-05 21:47:17.654900
std                              NaN
/Users/alexanderjameskershaw/Documents/HERMES/data/quarantine/silver/orders/not_null_order_status.parquet
                     order_timestamp  gross_amount  discount_amount  \
count                           5000   5000.000000      5000.000000
mean   2023-01-16 11:12:56.385199872    635.460056        13.873348
min              2023-01-01 00:02:36      7.150000         0.000000
25%    2023-01-08 19:21:18.750000128    252.697500         0.000000
50%              2023-01-16 10:06:34    471.060000         0.000000
75%    2023-01-24 01:32:52.249999872    881.402500        18.470000
max              2023-01-31 23:57:57   4029.280000       287.960000
std                              NaN    529.537228        26.291518

        net_amount   tax_amount           _silver_processed_at  \
count  5000.000000  5000.000000                           5000
mean    621.586708   124.317036  2026-07-05 21:41:04.089282560
min       6.430000     1.290000     2026-07-05 21:41:04.089282
25%     248.350000    49.670000  2026-07-05 21:41:04.089282048
50%     457.925000    91.585000  2026-07-05 21:41:04.089282048
75%     862.047500   172.407500  2026-07-05 21:41:04.089282048
max    3955.970000   791.180000     2026-07-05 21:41:04.089282
std     517.542541   103.508408                            NaN

                    _quarantine_time
count                           5000
mean   2026-07-05 21:47:17.179531776
min       2026-07-05 21:47:17.179532
25%    2026-07-05 21:47:17.179532032
50%    2026-07-05 21:47:17.179532032
75%    2026-07-05 21:47:17.179532032
max       2026-07-05 21:47:17.179532
std                              NaN